### ISSUE TITLE
[FEATURE REQUEST] Grinbox

### ISSUE THREAD

**Issue by skykingisepic** [NicolasFlamel1/Ledger-MimbleWimble-Coin#4]
Have you considered adding grinbox? This creates more a traditional email-like address to send/receive and eliminates the extra trouble with http to do port forwarding, ngrok, or being online to receive. Grinbox is the natural progression of original project.

**Comment by NicolasFlamel1** [comment]
No modern Grin wallets work with Grinbox anymore due to [Grin adopting Slatepacks as its universal transaction standard](https://github.com/mimblewimble/grin-rfcs/blob/master/text/0015-slatepack.md). Slatepacks use Tor as its synchronous transaction transport which the Grin Ledger hardware wallet app already supports via [offline identity keys](https://support.torproject.org/fr/relay-operators/offline-ed25519/).

**Comment by skykingisepic** [comment]
I would like to invite you to review our GRIN fork called EPIC Cash. We have a working fork of grinbox working with slatepacks. Part of our growth track includes Ledger support and would like to discuss with you. If you would like to check out an amazing community of hard working people feel free to join our dev focused group at https://t.me/joinchat/HX-saVVp_tuPgMbUINAQRw. My TG handle is the same as here and I am part of the devops team providing operational support for our small group of developers. Currently on Vite and will be listed on CoinStore and ChangeNOW by May. YT videos by Uncle Vigilante. Dozens of TG groups. Start at https://epic.tech. Looking forward to future interactions. Our dev who will be working on Ledger is known here as who-biz. Thanks for your time and consideration. Sky.

**Comment by NicolasFlamel1** [comment]
No thanks. I'm not interested in volunteering my time to any new projects at the moment.

**Comment by who-biz** [comment]
Hi Nicolas. I’m doing the EPIC ledger integration, and I noticed that your repository for `ledger-live` is not quite in sync with LedgerHQ’s.

I’ll likely be merging those upstream changes with your prior work (thank you). Thought I should offer to PR any useful changes I make.

 If for some reason you have no intent of merging a PR into your repos, let me know. Saves me some time if it’s a “no.” But, I would like to contribute back, as a more meaningful “thank you”.

Posting here on the existing issue, so as not to crowd `ledger-live`‘s tracker.

To be clear, my comments above do not mean grinbox support... just repo maintenance, etc.
