### ISSUE TITLE
App cannot be build on last api level for Stax

### ISSUE THREAD

**Issue by tdejoigny-ledger** [NicolasFlamel1/Ledger-MimbleWimble-Coin#6]
@NicolasFlamel1 could you please to help to solve tests issues for this [PR ](https://github.com/LedgerHQ/app-mimblewimblecoin/pull/6)

I have to fix the app because it doesn't build anymore on last api level.

ty for your help

**Comment by NicolasFlamel1** [comment]
Hey @tdejoigny-ledger. [This PR](https://github.com/LedgerHQ/app-mimblewimblecoin/pull/7/files) fixes the functional tests hanging on the Stax.

**Comment by tdejoigny-ledger** [comment]
ty @NicolasFlamel1
